[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.93.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/join"
  to = "https://forms.gle/BC2NG75YbErGD9Ak9"
  status = 302

[[redirects]]
  from = "/WGs"
  to = "https://www.dropbox.com/s/ynva0k222fxjrf8/WG_members.xlsx?dl=0"
  status = 302

[[redirects]]
  from = "/profile"
  to = "https://cigre-cyprus.org/Cyprus_NC_Profile.pdf"
  status = 302

[[redirects]]
  from = "/2023_NC_photos"
  to = "https://photos.app.goo.gl/pXYJkCHB5kkarj3R9"
  status = 302

[[redirects]]
  from = "/register"
  to = "https://forms.office.com/e/GZpfSmW39N"
  status = 302

[[redirects]]
  from = "/seminar"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_NmJhODBhYmYtNmU1ZS00Mjc0LTgyZTQtYWQwMTg2ODAzMzUw%40thread.v2/0?context=%7b%22Tid%22%3a%228dd1e6b4-8dac-408e-8d8d-6753e9800530%22%2c%22Oid%22%3a%222c7def7d-c1be-4982-9abd-6744164cbd75%22%7d"
  status = 302
